before_install: cd adaptive-arp-api-specs
language: java
jdk: oraclejdk8
before_script:
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_success:
- mkdir temp
- cd temp
- git clone https://github.com/AdaptiveMe/adaptive-arp-tools-generator.git
- cd adaptive-arp-api-specs
- ./gradlew assemble
env:
  global:
    secure: bTvMhMEC8TT9XYIO+ztgX6IuJopZaxR5X90oAHKtSJfcNgPQrDJMnNwrVC0g3GA4ZZcE/vmC3bXZLQcL51/UdiJCfY8S8VFM9KeMYYzzPA+XKJUqQx3eGPBP4YiP7U4xTJs73PoAmEoaXN0ytf8IpLK1UUdlIjATFYC1PLhDIPE=
