before_install: cd adaptive-arp-api-specs
language: java
jdk: oraclejdk8
before_script:
- export HOME=`pwd`
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
after_success:
- mkdir temp
- cd temp
- git clone https://${GH_TOKEN}:@github.com/AdaptiveMe/adaptive-arp-tools-generator.git
- cd adaptive-arp-tools-generator
- ./gradlew assemble
- ./gradlew installDist
- ./build/install/jenerator/bin/jenerator
- cd ..
- cd ..
- cat $HOME/.git/credentials
- cat $HOME/.gitconfig
env:
  global:
    secure: WIeNLQk7nYe/3JCSyBk1IRTJLlFHkQyKyWmpd6a5VD1uDNDRbtR/sDb/1TdcU4NWg9Uc0s3ZVHvvnFF0pqxJO5WcQ7eJReva27D3igIZBbLhaMONYg1O7I2MVzKxgMCRfhGexnz9UcEzZR/UrcjMxVh4qmx0X5K18Q2R5wVZpPI=
cache:
  directories:
  - $HOME/.gradle/
